export {default as Background} from "./Background.jpg"
export {default as Banner} from "./Banner.png"
export {default as Heading} from "./Heading.png"
export {default as Hand_Wash} from "./Hand Wash.png"
export {default as Face_Mask} from "./Face Mask.png"
export {default as Social_Distance} from "./Social Distance.png"
export {default as Infected} from "./Infected.png"
export {default as Recovered} from "./Recovered.png" 
export {default as Death} from "./Death.png"